version: '3'
services:
    ubuntu:
        container_name: ubuntu_your_project_name
        build:
          context: ./ubuntu/
        volumes:
            - ../html/project_folder:/var/www/html/
        ports:
            - 80:80
        links:
            - 'mysql'
        image: emersonunes/lamp_php7:latest
    mysql:
        image: mysql:8.0
        container_name: database_your_project_name
        volumes:
            - ./db:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: your_database
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
